"""
main.py
CSMID — CLI entry point.

Commands:
    collect --skin "AK-47 | Slate (Minimal Wear)"
        Fetches one live price record from Steam Market and stores it
        in market_history (creating the skins row if new).

    collect --watchlist rifles
        Collects every skin listed in data/watchlists/rifles.txt
        (or smgs / pistols / heavy / all_weapons, generated by
        tools/generate_watchlists.py).

    collect --all
        Legacy alias. Collects DEFAULT_WATCHLIST (kept for backward
        compatibility with existing scripts/cron jobs). Prefer
        --watchlist all_weapons going forward.

    list [--skin "..."] [--limit N]
        Shows the most recently collected market_history rows,
        optionally filtered to one skin, to verify collection worked.
"""

import argparse
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

from config import DEFAULT_WATCHLIST
from database import (
    SessionLocal,
    initialize_database,
    get_or_create_skin,
    insert_market_history,
    MarketHistory,
    Skin,
)
from scraper import SteamMarketScraper, SteamMarketError, SteamRateLimitError

# The generated per-category watchlists all live alongside DEFAULT_WATCHLIST
# in data/watchlists/. We derive the directory from DEFAULT_WATCHLIST rather
# than hardcoding a second path, so this stays correct regardless of what
# DEFAULT_WATCHLIST itself points to.
WATCHLISTS_DIR = DEFAULT_WATCHLIST.parent

# Names generated by tools/generate_watchlists.py. Used only to produce a
# friendlier error message when someone typos --watchlist; any *.txt file
# in WATCHLISTS_DIR will actually work.
KNOWN_WATCHLISTS = ["all_weapons", "rifles", "smgs", "pistols", "heavy"]


def print_banner() -> None:
    print("===================================")
    print(" CSMID - Counter Strike Market")
    print(" Intelligence Dataset")
    print("===================================")


def load_watchlist(path: Path) -> list[str]:
    """Reads market_hash_names from a watchlist file, one per line.
    Blank lines and lines starting with # are ignored."""
    if not path.exists():
        raise FileNotFoundError(
            f"Watchlist file not found: {path}\n"
            "Expected a plain text file with one market_hash_name per line."
        )

    names = []
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        names.append(stripped)
    return names


def resolve_watchlist_path(name: str) -> Path:
    """Maps a --watchlist NAME argument to its file under WATCHLISTS_DIR."""
    return WATCHLISTS_DIR / f"{name}.txt"


def get_recently_collected_names(session, since_hours: float) -> set[str]:
    """Returns the set of market_hash_names that already have a
    market_history row newer than `since_hours` ago. Used by --resume
    to skip skins a prior run already collected, instead of re-fetching
    (and re-spending rate-limit budget on) skins we already have.

    Assumes MarketHistory.collected_at_utc is stored as naive UTC,
    matching the column's name/existing usage elsewhere in this file.
    """
    cutoff = datetime.now(timezone.utc).replace(tzinfo=None) - timedelta(hours=since_hours)
    rows = (
        session.query(MarketHistory.market_hash_name)
        .filter(MarketHistory.collected_at_utc >= cutoff)
        .distinct()
        .all()
    )
    return {r[0] for r in rows}


def _store_record(session, market_hash_name: str, record) -> str:
    """Stores one record (if successful) and returns a short status
    string for the summary printout: 'collected', 'skipped_duplicate',
    or 'no_listing'."""
    if not record.success:
        return "no_listing"

    skin = get_or_create_skin(session, market_hash_name)
    row = insert_market_history(session, skin, record)
    if row is None:
        return "skipped_duplicate"

    return "collected"


def collect_batch(
    names: list[str],
    scraper: SteamMarketScraper,
    skip_names: set[str] | None = None,
) -> int:
    """Shared implementation for both --all and --watchlist NAME: fetches
    and stores a price record for every name in the list, printing a
    per-skin status line and a final summary. Returns exit code.

    If skip_names is given (from --resume), any name in it is skipped
    before hitting the scraper at all -- this is what lets a rerun after
    a rate-limit stop pick up where it left off instead of re-spending
    requests on skins we already collected.
    """
    skip_names = skip_names or set()
    to_fetch = [n for n in names if n not in skip_names]
    already_skipped = len(names) - len(to_fetch)

    if already_skipped:
        print(f"\u2139\ufe0f  Skipping {already_skipped} skin(s) already collected recently (--resume).")
    print(f"Collecting {len(to_fetch)} skins...\n")

    session = SessionLocal()
    counts = {"collected": 0, "skipped_duplicate": 0, "no_listing": 0}
    try:
        for name in to_fetch:
            try:
                record = scraper.fetch_price(name)
            except SteamRateLimitError as exc:
                # Whatever was already collected this run is committed
                # below in `finally` -- we just stop taking new ones.
                print(f"\n\u274c Rate limited on '{name}': {exc}")
                print(f"Stopping batch early. Progress so far: {counts}")
                session.commit()
                return 1
            except SteamMarketError as exc:
                print(f"\u26a0\ufe0f  '{name}' failed: {exc}")
                counts["no_listing"] += 1
                continue

            status = _store_record(session, name, record)
            counts[status] += 1

            symbol = {"collected": "\u2705", "skipped_duplicate": "\u2139\ufe0f", "no_listing": "\u26a0\ufe0f"}[status]
            print(f"{symbol} {name}: {status}")

        session.commit()
    except Exception:
        session.rollback()
        raise
    finally:
        session.close()

    print(f"\nDone. {counts['collected']} collected, "
          f"{counts['skipped_duplicate']} duplicates skipped, "
          f"{counts['no_listing']} had no listing/failed.")
    return 0


def cmd_collect(args: argparse.Namespace) -> int:
    """Fetch price(s) and store them. Handles --skin (one skin),
    --watchlist NAME (a generated category watchlist), and --all
    (legacy full-watchlist alias). Returns exit code."""
    scraper = SteamMarketScraper()

    def resolve_skip_names() -> set[str]:
        if not args.resume:
            return set()
        session = SessionLocal()
        try:
            skip_names = get_recently_collected_names(session, args.since_hours)
        finally:
            session.close()
        return skip_names

    if args.watchlist:
        path = resolve_watchlist_path(args.watchlist)
        try:
            names = load_watchlist(path)
        except FileNotFoundError as exc:
            print(f"\u274c {exc}")
            if args.watchlist not in KNOWN_WATCHLISTS:
                print(
                    f"'{args.watchlist}' isn't one of the generated watchlists "
                    f"({', '.join(KNOWN_WATCHLISTS)}). Check for typos, or run "
                    "tools/generate_watchlists.py if you haven't yet."
                )
            return 1
        return collect_batch(names, scraper, skip_names=resolve_skip_names())

    if args.all:
        try:
            names = load_watchlist(DEFAULT_WATCHLIST)
        except FileNotFoundError as exc:
            print(f"\u274c {exc}")
            return 1
        return collect_batch(names, scraper, skip_names=resolve_skip_names())

    # Single-skin mode
    try:
        record = scraper.fetch_price(args.skin)
    except SteamMarketError as exc:
        print(f"\u274c Scrape failed: {exc}")
        return 1

    if not record.success:
        print(
            f"\u26a0\ufe0f  Steam returned no listing data for '{args.skin}' "
            "(invalid name or zero listings). Nothing stored."
        )
        return 1

    session = SessionLocal()
    try:
        status = _store_record(session, args.skin, record)

        if status == "skipped_duplicate":
            print(
                f"\u2139\ufe0f  A record for this exact timestamp already exists "
                f"for '{args.skin}' \u2014 skipped duplicate insert."
            )
        else:
            session.commit()
            print(f"\u2705 Collected '{args.skin}':")
            print(f"   lowest_price:  {record.lowest_price}")
            print(f"   median_price:  {record.median_price}")
            print(f"   volume:        {record.volume}")
            print(f"   collected_at:  {record.collected_at_utc}")
    except Exception:
        session.rollback()
        raise
    finally:
        session.close()

    return 0


def cmd_list(args: argparse.Namespace) -> int:
    """Print the most recent market_history rows."""
    session = SessionLocal()
    try:
        query = (
            session.query(MarketHistory)
            .order_by(MarketHistory.collected_at_utc.desc())
        )

        if args.skin:
            query = query.filter(MarketHistory.market_hash_name == args.skin)

        rows = query.limit(args.limit).all()

        if not rows:
            print("No market_history records found.")
            return 0

        print(f"{'collected_at_utc':<26} {'lowest':>8} {'median':>8} {'vol':>8}  market_hash_name")
        print("-" * 90)
        for row in rows:
            print(
                f"{str(row.collected_at_utc):<26} "
                f"{row.lowest_price if row.lowest_price is not None else '-':>8} "
                f"{row.median_price if row.median_price is not None else '-':>8} "
                f"{row.volume if row.volume is not None else '-':>8}  "
                f"{row.market_hash_name}"
            )
    finally:
        session.close()

    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="main.py",
        description="CSMID - Counter Strike Market Intelligence Dataset collector",
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    collect_parser = subparsers.add_parser(
        "collect", help="Collect a live price record for one skin or a whole watchlist"
    )
    collect_group = collect_parser.add_mutually_exclusive_group(required=True)
    collect_group.add_argument(
        "--skin",
        help='Exact Steam market_hash_name, e.g. "AK-47 | Slate (Minimal Wear)"',
    )
    collect_group.add_argument(
        "--watchlist",
        metavar="NAME",
        help=(
            "Collect every skin in data/watchlists/NAME.txt, e.g. "
            "--watchlist rifles. Generated by tools/generate_watchlists.py "
            f"(available: {', '.join(KNOWN_WATCHLISTS)})."
        ),
    )
    collect_group.add_argument(
        "--all",
        action="store_true",
        help="[legacy] Collect DEFAULT_WATCHLIST. Prefer --watchlist all_weapons.",
    )
    collect_parser.add_argument(
        "--resume",
        action="store_true",
        help=(
            "Skip skins already collected within --since-hours (default 6h). "
            "Use this to pick up a --watchlist/--all run after a rate-limit "
            "stop without re-fetching skins you already have. No effect with --skin."
        ),
    )
    collect_parser.add_argument(
        "--since-hours",
        type=float,
        default=6.0,
        help="Lookback window in hours for --resume (default: 6).",
    )
    collect_parser.set_defaults(func=cmd_collect)

    list_parser = subparsers.add_parser(
        "list", help="List recently collected market_history rows"
    )
    list_parser.add_argument(
        "--skin",
        default=None,
        help="Filter to one exact market_hash_name",
    )
    list_parser.add_argument(
        "--limit",
        type=int,
        default=20,
        help="Max rows to show (default: 20)",
    )
    list_parser.set_defaults(func=cmd_list)

    return parser


def main() -> int:
    print_banner()
    initialize_database()
    print("Project initialized successfully!")

    parser = build_parser()
    args = parser.parse_args()
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())